FROM pyecvl

RUN python3 -m pip install --upgrade --no-cache-dir \
      sphinx sphinx_rtd_theme

COPY . /pyecvl
WORKDIR /pyecvl

RUN python3 setup.py build_py && \
    python3 setup.py install --skip-build && \
    make -C docs/source html
