FROM ecvl-no-eddl

RUN apt-get -y update && apt-get -y install --no-install-recommends \
      python3-dev \
      python3-pip

RUN python3 -m pip install --upgrade --no-cache-dir \
      setuptools pip && \
    python3 -m pip install --upgrade --no-cache-dir \
      numpy 'pybind11<2.6' pytest

# Run git submodule update [--init] --recursive first
COPY . /pyecvl
WORKDIR /pyecvl
ENV ECVL_EDDL=OFF ECVL_WITH_DICOM=OFF ECVL_WITH_OPENSLIDE=OFF
RUN python3 setup.py install
