FROM dhealth/dev-ecvl-minimal

ENV ECVL_EDDL=OFF ECVL_WITH_DICOM=OFF ECVL_WITH_OPENSLIDE=OFF

COPY . /pyecvl
WORKDIR /pyecvl

RUN apt-get -y update && apt-get -y install --no-install-recommends \
      python3-dev \
      python3-pip && \
    python3 -m pip install --upgrade --no-cache-dir \
      pip setuptools && \
    python3 -m pip install --upgrade --no-cache-dir \
      numpy 'pybind11<2.6' pytest && \
    python3 setup.py install
